language: android
env:
  global:
    - ADB_INSTALL_TIMEOUT=2
    - QEMU_AUDIO_DRV=none # Remove audio

android:
  components:
    # Use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by the project
    - build-tools-28.0.3

    # The SDK version used to compile the project
    - android-28
    # The SDK version used for the Emulator
    - android-17

    # Additional components
    - extra-google-google_play_services
    - addon-google_apis-google-28
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17

  licenses:
    - android-sdk-license-.+
    - '.+'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - echo no | android create avd --force -n test -t android-17 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v

script:
  - ./gradlew clean installDebug
  - ./gradlew check
  - ./gradlew testDebugUnitTest
  - ./gradlew connectedDebugAndroidTest
  - ./gradlew test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_install:
  - yes | sdkmanager "platforms;android-28"
  - openssl aes-256-cbc -K $encrypted_bfac04c8d83b_key -iv $encrypted_bfac04c8d83b_iv -in app/google-services.json.enc -out /google-services.json -d

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
